name: Publish NuGet Package

on:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Build C# project
      working-directory: ./csharp
      run: |
        dotnet build spoonacular.csproj -c Release
    
    - name: Pack NuGet
      working-directory: ./csharp
      run: |
        dotnet pack spoonacular.csproj -c Release -o ./out
    
    - name: Publish to GitHub Packages
      working-directory: ./csharp
      run: |
        dotnet nuget push ./out/*.nupkg \
          --source https://nuget.pkg.github.com/kiwiczanga/index.json \
          --api-key ${{ secrets.GITHUB_TOKEN }}
